"""adding month and year

Revision ID: 48285767aafb
Revises: 6aba8ef37cef
Create Date: 2022-08-16 16:09:42.233950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48285767aafb'
down_revision = '6aba8ef37cef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card_details', sa.Column('month', sa.String(length=20), nullable=True))
    op.add_column('card_details', sa.Column('year', sa.String(length=20), nullable=True))
    op.drop_column('card_details', 'exDate')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card_details', sa.Column('exDate', sa.VARCHAR(length=20), nullable=True))
    op.drop_column('card_details', 'year')
    op.drop_column('card_details', 'month')
    # ### end Alembic commands ###
