"""Adding cardRef

Revision ID: 6aba8ef37cef
Revises: a4db7602405f
Create Date: 2022-08-16 11:24:16.303128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6aba8ef37cef'
down_revision = 'a4db7602405f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card_details', sa.Column('cardRef', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('card_details', 'cardRef')
    # ### end Alembic commands ###
