"""cardDetail Modification

Revision ID: 6d0cedb309e7
Revises: e33687354412
Create Date: 2022-08-17 12:39:22.508045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d0cedb309e7'
down_revision = 'e33687354412'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('card_details', 'otp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card_details', sa.Column('otp', sa.VARCHAR(length=20), nullable=True))
    # ### end Alembic commands ###
