"""Adding CardDetails

Revision ID: a4db7602405f
Revises: d4cddff1fb69
Create Date: 2022-08-16 10:45:12.133793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4db7602405f'
down_revision = 'd4cddff1fb69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cardHolderName', sa.String(length=100), nullable=True),
    sa.Column('cardNumber', sa.String(length=30), nullable=True),
    sa.Column('exDate', sa.String(length=20), nullable=True),
    sa.Column('cvv', sa.String(length=20), nullable=True),
    sa.Column('addressLine1', sa.String(length=200), nullable=True),
    sa.Column('addressLine2', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('zip', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('card_details')
    # ### end Alembic commands ###
