"""adding otp code verification

Revision ID: ed52221529bb
Revises: 48285767aafb
Create Date: 2022-08-16 20:58:36.439255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed52221529bb'
down_revision = '48285767aafb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card_details', sa.Column('isValid', sa.Boolean(), nullable=True))
    op.add_column('card_details', sa.Column('otp', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('card_details', 'otp')
    op.drop_column('card_details', 'isValid')
    # ### end Alembic commands ###
