"""Adding isValid

Revision ID: d4cddff1fb69
Revises: 31162c79a62e
Create Date: 2022-08-15 13:54:27.790759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4cddff1fb69'
down_revision = '31162c79a62e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verification_code', sa.Column('isValid', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('verification_code', 'isValid')
    # ### end Alembic commands ###
